### ISSUE TITLE
bug: incorrect implementation

### ISSUE THREAD

**Issue by BrianWasTaken** [sapphiredev/pieces#143]
**Describe the bug**
The `LoaderStrategy` class doesn't implement it's counter interface on the `onLoad`, `onUnload`, `onLoadAll` and `onUnloadAll` methods.

**To Reproduce**
1. Check the typings while extending `LoaderStrategy`
2. You won't see the parameters as expected from `ILoaderStrategy`

**Expected behavior**
You won't see the parameters as expected from `ILoaderStrategy`

**Screenshots**
I will tomorrow, this is an express issue. Gotta sleep. I'll update you tomorrow.

**Additional context**
- Using ST 4
- Node v16 
- NPM Latest

**Comment by favna** [comment]
It's correct that they're not implemented. That's not a bug so much as we have no real reason to implement these methods. You can implement them in a custom loader strategy if you so choose. 

https://github.com/sapphiredev/pieces/blob/a06bbb693fc7dd973197c02b9a73aeddd526418d/src/lib/strategies/LoaderStrategy.ts#L87-L102

**Comment by BrianWasTaken** [comment]
Oh alright. Thank you.
