### ISSUE TITLE
request: bun compat

### ISSUE THREAD

**Issue by castdrian** [sapphiredev/pieces#339]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

it'd be nice if /pieces would run on bun, seems to be the only part that is having trouble

### Desired solution

haven't looked alto much into it but it's probably somewhat related to the module resolution within pieces, since it complains about all paths being `undefined/thing/module.js`

### Alternatives considered

nop

### Additional context

https://adriancastro.dev/wujc8lds16bo.png

**Comment by favna** [comment]
Duplicate of https://github.com/sapphiredev/framework/issues/671

TL;DR Unfortunately its on bun to fix their node apis

**Comment by castdrian** [comment]
ah I see, those bun people need to get their buns bunning smh
