### ISSUE TITLE
bug: Bun not loading classes due to clientUsesESModules being set to false.

### ISSUE THREAD

**Issue by spartacus04** [sapphiredev/pieces#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

I'm using bun tu run my djs bot, however both listeners and commands aren't loaded. Because of a error:

```stacktrace
error: A compatible class export was not found. [/home/username/Source/mybot/src/commands/other/say.ts]
 path: "/home/username/Source/mybot/src/commands/other/say.ts"
      at new _LoaderError (/home/username/Source/mybot/node_modules/@sapphire/pieces/dist/esm/lib/errors/LoaderError.mjs:14:5)
      at new _MissingExportsError (/home/username/Source/mybot/node_modules/@sapphire/pieces/dist/esm/lib/errors/MissingExportsError.mjs:6:5)
      at /home/username/Source/mybot/node_modules/@sapphire/pieces/dist/esm/lib/strategies/LoaderStrategy.mjs:71:13
```

I've debugged a bit and it looks like LoaderStrategy will import the file in the wrong way.

When I manually set the `clientUsesESModules` property to true it worked flawlessly.

### Steps To Reproduce

1. Use Bun to either load commands or listeners from .ts files
2. Error on load

### Expected behavior

For the framework to load the commands/listeners successfully

### Screenshots

![image](https://github.com/sapphiredev/pieces/assets/52862005/dcd077d3-05a5-46dd-9c92-e37a6281a54f)
![image](https://github.com/sapphiredev/pieces/assets/52862005/13d2f214-edc3-4782-a262-bd182093962c)

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
    CPU: (16) x64 AMD Ryzen 7 5700U with Radeon Graphics
    Memory: 9.46 GB / 14.94 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 21.0.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.1.0 - ~/.local/share/pnpm/npm
    pnpm: 8.15.3 - ~/.local/share/pnpm/pnpm
    bun: 1.1.6 - ~/.local/share/pnpm/bun
```

**Comment by favna** [comment]
Do you have a `package.json` file? We use that file to determine if the project is using ESM or not. Specifically, in this file: https://github.com/sapphiredev/pieces/blob/7eb28a976f9ddb3cd596805977cb78b0eacb394c/src/lib/internal/RootScan.ts

Assuming you have a `package.json` just add `"type": "module"` and your code will run as ESM. Alternatively change your `"main": "..."` with `"module": "..."` as per line 104/5.

I don't really see any reliable different way to set the project to use ESM that will support all of Node, Bun, and Deno.

**Comment by spartacus04** [comment]
Adding `"type": "module"` fixed it, thanks!
